apiVersion: v1
kind: Service
metadata:
  name: konga-final
  namespace: kong
spec:
  selector:
    app: konga
  ports:
  - name: http
    port: 1337
    targetPort: 1337
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-final
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      serviceAccountName: secret-manager-individual-sa
      containers:
      - name: konga
        image: pantsel/konga
        ports:
        - containerPort: 1337
        env:
        - name: NODE_ENV
          value: development
        - name: DB_ADAPTER
          value: postgres
        - name: KONGA_HOOK_TIMEOUT
          value: "10000"
        - name: KONG_PG_PORT
          value: "5432"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: final-secrets-kong-local     
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: final-secrets-kong-local
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: final-secrets-kong-local
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: final-secrets-kong-local
              key: DB_NAME
        volumeMounts:
        - name: secret-manager
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secret-manager
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secretpc-final
            

