apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretpc-final
  namespace: kong
spec:
  provider: aws
  secretObjects:
  - secretName: poc/kong/rds #arn:aws:secretsmanager:ap-southeast-1:432125190050:secret:poc/kong/rds-4dT9Rc      # name from secretmanager(secret name)
    type: Opaque
    data:
    - objectName: DB_HOST
      key: DB_HOST
    - objectName: DB_NAME
      key: DB_NAME
    - objectName: DB_USER
      key: DB_USER
    - objectName: DB_PASSWORD
      key: DB_PASSWORD
  parameters:
    objects: |
        - objectName: "poc/kong/rds"
          objectType: "secretsmanager"
          jmesPath:
            - path: "DB_HOST"
              objectAlias: "DB_HOST"
            - path: "DB_NAME"
              objectAlias: "DB_NAME"
            - path: "DB_USER"
              objectAlias: "DB_USER"
            - path: "DB_PASSWORD"
              objectAlias: "DB_PASSWORD"
  secretObjects:
    - secretName: final-secrets-kong-local
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
---
# arn:aws:secretsmanager:ap-southeast-1:432125190050:secret:poc/kong/rds-4dT9Rc